data_url: "/Users/tjscott23/Documents/MLOps_PL_project/Data/IBM_HR_Attrition.csv"
t_data_url: "Data/sample_Attrition.csv"
target: "attrition"

test_size: 0.2
random_state: 12345

model:
  n_estimators: 100
  max_depth: 10

numeric_columns:
  - age
  - daily_rate
  - distance_from_home
  - education
  - environment_satisfaction
  - job_involvement
  - job_level
  - job_satisfaction
  - hourly_rate
  - monthly_income
  - monthly_rate
  - num_companies_worked
  - percent_salary_hike
  - relationship_satisfaction
  - stock_option_level
  - performance_rating
  - total_working_years
  - training_times_last_year
  - work_life_balance
  - years_at_company
  - years_in_current_role
  - years_since_last_promotion
  - years_with_curr_manager

categorical_columns:
  - business_travel
  - department
  - education_field
  - gender
  - job_role
  - marital_status
  - over_time

performance_thresholds:
  min_accuracy: 0.35
  min_f1: 0.30

drift_threshold: 0.50